version: "4"
services:
  reverseproxy:
    build:
      context: ./udagram_reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram_api_user
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram_api_feed
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram_frontend
    image: udagram-frontend