
name: DockerHub Deployment
on:
  push:
    branches:
      - 'main'

jobs:
    udagram-api-feed:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-api-feed
            file: ./udagram-api-feed/Dockerfile
            push: true
            tags: ezekielhub/udagram-api-feed


    udagram-api-user:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-api-user
            file: ./udagram-api-user/Dockerfile
            push: true
            tags: ezekielhub/udagram-api-user


    udagram-frontend:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-frontend
            file: ./udagram-frontend/Dockerfile
            push: true
            tags: ezekielhub/udagram-frontend


    udagram-reverseproxy:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-reverseproxy
            file: ./udagram-reverseproxy/Dockerfile
            push: true
            tags: ezekielhub/udagram-reverseproxy
