
name: Docker Container
on:
  push:
    branches:
      - 'main'

jobs:
    udagram-api-feed:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram_api_feed
            file: ./udagram_api_feed/Dockerfile
            push: true
            tags: ezekielhub/udagram-api-feed


    udagram-api-user:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram_api_user
            file: ./udagram_api_user/Dockerfile
            push: true
            tags: ezekielhub/udagram-api-user


    udagram-frontend:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram_frontend
            file: ./udagram_frontend/Dockerfile
            push: true
            tags: ezekielhub/udagram-frontend:v6


    udagram-reverseproxy:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram_reverseproxy
            file: ./udagram_reverseproxy/Dockerfile
            push: true
            tags: ezekielhub/udagram-reverseproxy:v1
