on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username : ${{ secrets.DOCKER_HUB_USERNAME}}
        password : ${{ secrets.DOCKER_HUB_ACCESS}}
    - name: Build and push to Docker Hub
      uses: docker/push-action@v2
      with:
        context: .
        push: true
        tags: ezekielhub/udagram-api-feed:v1, ezekielhub/udagram-api-user:v1, ezekielhub/udagram-frontend:local, ezekielhub/reverseproxy:v1