name: Reverseproxy Docker

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

    
        steps:
        - name: Checkout 
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram_reverseproxy
            file: ./udagram_reverseproxy/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/udacity_udagram_reverseproxy:v1
            cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/udacity_udagram_reverseproxy:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/udacity_udagram_reverseproxy:buildcache,mode=max
